### ISSUE TITLE
ijson.items(file, prefix) waits for EOF

### ISSUE THREAD

**Issue by green-green-avk** [ICRAR/ijson#104]
**Describe the bug**
`ijson.items(file, prefix)` waits for EOF before yielding any values.

**How to reproduce**
The input (file object `f`) represents an infinite stream of JSON objects: `{"a":1} {"b":2} ...`
```python3
gen = ijson.items(f, "", multiple_values=True)
for v in gen:
    print(v)
```

**Expected behavior**
Yield a value as soon as an object is parsed. Don't wait for EOF.

**Execution information:**
 - Python version: 3.11.2
 - ijson version: 3.2.3
 - ijson backend: python
 - ijson installation: pip
 - OS: Linux

**Additional context**
It looks similar to #72 but I see no reason to use any `async` here as it is not an asynchronous situation at all: just a simplest stream pull parser use case.

**Comment by rtobar** [comment]
Thanks @green-green-avk for the interesting report. Do you have an example file that can be used for testing this? In particular, I'd like to understand/confirm that you *really* don't get any values yielded until you hit the EOF. How are 100% certain of that? The example code looks correct of course, so I suppose your report is based on observations of some kind.

If `f` is an actual file on disk, and you opened it via `open`, you could try adding a `print(f.tell())` in your for loop to see how much the file has been advanced every time you get a value.

**Comment by rtobar** [comment]
Also: does this happen with other backends? Just noticed this was reported for the python backend, so maybe (hopefully!) ithe issue, if there's one, is specific to this backend.

**Comment by green-green-avk** [comment]
Uh. Huh. It's about **streams**, not files at all.

Please, consider this one-liner repro case:
```bash
python3 -c "$(echo -en 'import time\nwhile(True): print("{\"test\":1}", flush=True);time.sleep(1)')" | python3 -c "$(echo -en 'import sys\nimport ijson\nfor v in ijson.items(sys.stdin.buffer, "", multiple_values=True): print(v)')"
```

**Comment by green-green-avk** [comment]
Ouch, it seems, I missed `buf_size=1` stanza so bad here...

It works:
```bash
python3 -c "$(echo -en 'import time\nwhile(True): print("{\"test\":1}", flush=True);time.sleep(1)')" | python3 -c "$(echo -en 'import sys\nimport ijson\nfor v in ijson.items(sys.stdin.buffer, "", multiple_values=True, buf_size=1): print(v)')"
```

However, I think, the exact semantics of the `buf_size` option deserves to be [documented](https://pypi.org/project/ijson/#options-1).

**Comment by green-green-avk** [comment]
Aha!

In this case, we just need to add an option to use [read1](https://docs.python.org/3/library/io.html#io.BufferedIOBase.read1) instead.

**Comment by rtobar** [comment]
Or try with `sys.stdin.buffer.raw` (if that exists). Or chose a `buf_size` that better matches your situation.

I'd try to exhaust your options before jumping in and trying to implement a new feature that seems to cover only a very minor corner-case, bit would take some effort to get right (and thus I'd be a bit unwilling to implement myself, although I'd be happy to review PRs). If you really want to go down that route, please let's track that on a separate issue to keep things separate.

Also, could I ask again if you could address the questions I posed in my previous comment? I want to confirm there's no actual issue in ijson ATM, and that this is mostly about managing expectations when using stdin.
