### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by corneliusroemer** [ICRAR/ijson#111]
**Is your feature request related to a problem? Please describe.**

Thanks for ijson! Perfect tool for streaming json that saved my day!

I've noticed there are quite a few commits on main that aren't part of a release yet! Would be great if you could make a release :)

https://github.com/ICRAR/ijson/compare/v3.2.3...master

**Comment by rtobar** [comment]
@corneliusroemer can do! You're right that a release is in order, it's been a while since the last one. I had some ideas of things to further include in a new version, but that can wait. I'll post here once it's up there
