### ISSUE TITLE
Replace `mktemp` method with `NamedTemporaryFile`

### ISSUE THREAD

**Issue by ZuhairORZaki** [ICRAR/ijson#117]
### Overview

In file: [setup.py](https://github.com/ICRAR/ijson/blob/v3.3.0/setup.py#L61), there is a method that creates a temporary file using an unsafe API `mktemp`. The use of this method is discouraged in the Python documentation. iCR suggested that a temporary file should be created using `NamedTemporaryFile` or `mkstemp` which is a safe API. iCR replaced the usage of `mktemp` with `NamedTemporaryFile`. Read more about tempfile's deprecated functions [here](https://docs.python.org/3/library/tempfile.html#deprecated-functions-and-variables).

```diff
--- /workspace/source/setup.py
+++ /workspace/source/setup.py
@@ -7,7 +7,6 @@
 
 import glob
 import os
-import platform
 import shutil
 import tempfile
 
@@ -58,7 +57,7 @@
     compiler = ccompiler.new_compiler(verbose=1)
     sysconfig.customize_compiler(compiler) # CC, CFLAGS, LDFLAGS, etc
 
-    fname = tempfile.mktemp(".c", "yajl_version")
+    fname = tempfile.NamedTemporaryFile(".c", "yajl_version").name
     try:
         with open(fname, "wt") as f:
             f.write('''
```

### Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed - to improve global software supply chain security.

The bug is found by running the iCR tool by [OpenRefactory, Inc.](https://openrefactory.com/) and then manually triaging the results.

**Comment by potiuk** [comment]
Hello here. I am an Apache Airflow maintainer - and we are looking - together with Open Refactory and Alpha-Omega at improving Apache Airflow's Supply Chain security. This one is one of the bugs we found during the checks. We are going to talk about the whole project we are running soon at Airflow Summit - https://airflowsummit.org/ and it would be great to have more succeess stories (we are just starting and expect more activities to come) 

Would it be possible to prioritise this fix ?

**Comment by rtobar** [comment]
Hi @potiuk, thanks for getting in touch. While I'm not 100% sure, the first message felt more automatically generated and hence I didn't feel urgency in replying, while yours feels more individually targeted.

I will look into this. I agree with the diagnosis, although I feel the proposed solution might not be optimal, so I won't apply it as-is. I also personally feel no urgency about this particular incident -- in the worst case some malicious actor can either force the installation of the package to *not* include the C extension, affecting runtime performance,  or make the installation of the build fail, all with very slim chances and non-obvious gains. But like I said, I'll check it out when I can spare some time, I'll post an update here.

Thanks again for the message, and good luck with your work and presentation!

**Comment by potiuk** [comment]
> I also personally feel no urgency about this particular incident 

Sure - take your time :)

**Comment by rtobar** [comment]
Fixed on `master`, thanks again for the report!

**Comment by potiuk** [comment]
Thank you !
