### ISSUE TITLE
Incomplete parse with trailing garbage

### ISSUE THREAD

**Issue by doerwalter** [ICRAR/ijson#123]
**Is your feature request related to a problem? Please describe.**

When parsing JSON that contains trailing garbage, the last chunk read from the file will be completely ignored, even if that junk still starts with proper JSON.

For example the following script

```python
import io, ijson
for x in ijson.basic_parse(io.StringIO('{"x": "y"}#')):
    print(x)
```

doesn't output anything, but throws the following exception:

```
Traceback (most recent call last):
  File "/Users/walter/x/ijson_imcomplete.py", line 2, in <module>
    for x in ijson.basic_parse(io.StringIO('{"x": "y"}#')):
             ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ijson.common.IncompleteJSONError: parse error: trailing garbage
                             {"x": "y"}#
                     (right here) ------^
```

**Describe the solution you'd like**

`ijson` should output the following events before the `ijson.common.IncompleteJSONError` exception gets raised:

```
('start_map', None)
('map_key', 'x')
('string', 'y')
('end_map', None)
```

This should work with all backends (I'm using `ijson.backends.yajl2_c`)

**Describe alternatives you've considered**

There probably isn't a reasonable workaround here. If `IncompleteJSONError` had information about the error position I could try to extract the valid part from the chunk and try to continue parsing with that part, but I don't know whether this is possible at all, or if this would confuse the parser state. Also it is probably quite complicated to fake a readable stream where it's possible to stuff new data into it after the error. And as `IncompleteJSONError` does *not* have the error position, this is useless anyway. Trying to parse the error position from the `(right here) ------^` part of the exception message is really something I'd like to avoid.

So, tt really would be best if `ijson` would parse as much as is available before throwing the `ijson.common.IncompleteJSONError` exception.

**Comment by rtobar** [comment]
Thanks @doerwalter for the very clear description of the issue.

I think this is a reasonable expectation. At first I was worried that this was a limitation of the underlying `yajl` library, but after thinking about it it makes sense that the library produces and notifies about all relevant events before detecting the issue. To rule this out I tried using the push interfaces provided by `ijson`, which you can also use:

```python
import io, ijson

events = ijson.sendable_list()
json = b'{"x": "y"}#'
coro = ijson.basic_parse_coro(events)

try:
    coro.send(json)
    coro.close()
except Exception as ex:
    print(ex)

print("Printing events now")
for event in events:
    print(event)
```

All backends I tried (`yajl2_c`, `yajl`2, `yajl2_cffi` and `python`) show the events as expected. The `python` backend fails in a different way, but it fails nevertheless. In other words, `yajl`, and our own pure python parser, do generate all relevant events.

The difference in behaviour is in how we internally wrap the push interfaces into the pulling API. In particular, I'm talking about https://github.com/ICRAR/ijson/blob/master/src/ijson/utils.py#L45, where we don't yield events in the case of an error during parsing (there's some similar logic in https://github.com/ICRAR/ijson/blob/master/src/ijson/backends/ext/_yajl2/reading_generator.c#L59).

I'll have a look at this and change the behaviour of our generators so they more eagerly publish events on the face of errors, which is definitely a better out-of-the-box experience for users. In the meantime you can try using the push interfaces and see if that works for you.

**Comment by rtobar** [comment]
@doerwalter please try out the contents of the `issue-123` branch. I feel happy with what's in there, and I've included a test that verifies all events are seen in the face of errors. Although it limits itself to testing `basic_parse` like you did, I think it should work similarly for all generators.

After confirmation from your side I'll merge to `master`.

**Comment by doerwalter** [comment]
My test script now works, no matter whether I use

```python
import ijson
```

or

```
import ijson.backends.yajl2_c as ijson
```

I haven't tried any other interface except for `basic_parse()`.

**Comment by rtobar** [comment]
Merged to `master` now. I won't be making a release to PyPI yet, I'm still tying some knots before cutting one.
