### ISSUE TITLE
Memory leak in asyncio interface

### ISSUE THREAD

**Issue by dizballanze** [ICRAR/ijson#30]
Hi.
I think I've found a memory leak in asyncio interface.
I'm using latest `ijson==3.0.4` with python3.7 on macos mojave.

Here's an example of the leak:

```python
import asyncio
import ijson.backends.yajl2_c as ijson


class AsyncReaderWrapper:
    def __init__(self, stream):
        self._stream = stream

    async def read(self, value: int):
        if value == 0:
            return b""
        return self._stream.read()


async def parse_json_async(json_fp):
    async for objects in ijson.parse_async(AsyncReaderWrapper(json_fp)):
        yield objects


async def amain():
    events = 0
    with open("100mb.json", "rb") as json_fp:
        async for prefix, event, value in parse_json_async(json_fp):
            events += 1

    print(f"Got {events}")
    print("Press any key...")
    input()


if __name__ == "__main__":
    asyncio.run(amain())

```

And a sync version for comparison:

```python
import ijson.backends.yajl2_c as ijson


def main():
    events = 0
    with open("100mb.json", "rb") as json_fp:
        for prefix, event, value in ijson.parse(json_fp):
            events += 1

    print(f"Got {events}")
    print("Press any key...")
    input()


if __name__ == "__main__":
    main()
```

I've used memory_profiler on both and got following results:

Async version

![image](https://user-images.githubusercontent.com/952028/83053759-e69ffe80-a059-11ea-9646-a6829fff1db8.png)

Sync version:
![image](https://user-images.githubusercontent.com/952028/83053812-fe778280-a059-11ea-9ec4-8f9ff4f69d9c.png)

Looks like when I'm using async interface, memory released only after the whole file was processed.
I tried all backends and all have comparable results.

**Comment by dizballanze** [comment]
Ohh. That's my fault. I forgot to pass `value` to the file's `read` method. Sorry :)

**Comment by rtobar** [comment]
I'm happy you found the problem in the code (and also to learn that people are actually using the async interfaces!).
