### ISSUE TITLE
Arm64 wheel

### ISSUE THREAD

**Issue by tsahee** [ICRAR/ijson#35]
With the increase of Arm CPUs in datacenters and the upcoming Apple migration to Arm, the use of Python on these platforms is growing. However, installing Python modules without Wheels often fails or it is very slow. The error messages users see are not clearly identifying the problem as missing build dependency. Publishing a Wheel is typically low effort, just a few lines in the build script. For users this saves significant time by avoiding troubleshooting and not having to wait for build processes to finish.

Ijson uses cibuildwheel via GitHub actions. If you're open to it - the easiest way to create arm64 wheels would be to move to cibuildwheel on travis.com. I would be happy to try and create a pull request in that direction.

**Comment by rtobar** [comment]
@tsahee thanks a lot for the interest, I agree that having Arm wheels would certainly be a win.

I would imagine cibuildwheel would take care of these details, but I personally would like to learn what will happen with arm@Macs in particular. I don't remember seeing anything on Travis yet pointing to supporting this yet, and I don't know how the python ecosystem is making itself ready for it: is it envisioned that double-arch wheels will be produced, or different wheels for different archs will be the way to go?

Anyway, sure, I'm definitely open to a PR with this support. As a minimum it should support what we currently support via GH actions. The changes should point to the test PyPI server and make it very clear how to change it to the main one once they are adopted. Uploading to PyPI should only happen on tag pushes, but for the purpose of testing the changes should work on any push, and should make it again very clear what to change to publish only on tags.

**Comment by tsahee** [comment]
Sent an initial PR. Would be happy to know what you think about it.

I don't really know what's the plan for arm@Mac wheel. Will be interesting to find out.

**Comment by rtobar** [comment]
Changes now present in the `master` branch. A new `3.1.2.post0` release will be created using the new infrastructure, and therefore containing arm64 wheels.

**Comment by rtobar** [comment]
`3.1.2.post0` released.
