### ISSUE TITLE
PyInstaller Hooks

### ISSUE THREAD

**Issue by Steelsmasher** [ICRAR/ijson#37]
It would be nice if ijson had PyInstaller hooks so we can bundle it as part of a standalone application.

This code from __init.py__ causes problems when building with PyInstaller because dynamically loaded modules are not included
`return importlib.import_module('ijson.backends.' + backend)`

For now I'm getting around this by specifying the below in the .spec file
`hiddenimports=['ijson.backends.yajl2_c']`

**Comment by rtobar** [comment]
@Steelsmasher I'm not familiar with PyInstaller, so while I understand your question at a high level, I'm not sure what is *precisely* being requested here.

I don't think I will personally invest time on implementing this; however I'm happy to discuss further and review PRs of course.

**Comment by Steelsmasher** [comment]
It's probably better I submit a hook to [PyInstaller](https://github.com/pyinstaller/pyinstaller-hooks-contrib) itself rather than asking you to support it. Though someone who may want to include this package in a standalone executable may run into problems if they use PyInstaller.

The alternative is having the 'backends' modules be imported normally instead of dynamically, though I'm sure you had a reason for doing it that way.

**Comment by rtobar** [comment]
@Steelsmasher yes, the dynamic loading of backends is one of the strengths of ijson, as different backends might not be available to users depending on s number of factors.

The only backend that is guaranteed to always be there is the python backend, but that is almost two orders of magnitude slower than the fastest backends. Back in the day the python backend was always loaded by default, but that led to users having an extremely slow experience by default.
