### ISSUE TITLE
Please publish ijson 3.1.2.post0 sdist

### ISSUE THREAD

**Issue by sunpoet** [ICRAR/ijson#39]
There is no ijson 3.1.2.post0 sdist on PyPI. Could you please publish it?
Thanks.

**Comment by rtobar** [comment]
Thanks @sunpoet for pointing this out. In 3.1.2.post0 we moved the automatic uploading of PyPI artifacts from GitHub actions to Travis, and this slipped through unnoticed until now (so everyone is using pre-compiled wheels, which is itself great!).

Anyhow, I've just uploaded an sdist for this latest version. I'll make a note to add the necessary step in our CI pipeline to upload this in future releases.

**Comment by sunpoet** [comment]
Thanks!
