### ISSUE TITLE
Python Backend Allows Leading 0s in Numbers

### ISSUE THREAD

**Issue by lwoerdeman** [ICRAR/ijson#40]
The python backend will not throw an IncompleteJSONError when parsing a JSON file that has leading 0s in the numeric value. When using the yajl2_c parser, the error is thrown as expected.

For example, when given this invalid JSON, both backends should throw the error.
```json
{"should_fail": 001}
```

However, as the output shows, only the yajl2 backend fails, while the python parser parses `001` as `1`
```python
>>> import ijson.backends.python as ijson
>>> print ([x for x in ijson.items('{"should_fail": 001}', '')])
[{'should_fail': 1}]
>>> import ijson.backends.yajl2_c as ijson
>>> print ([x for x in ijson.items('{"should_fail": 001}', '')])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
ijson.common.IncompleteJSONError: parse error: after key and value, inside map, I expect ',' or '}'
                       {"should_fail": 001}
                     (right here) ------^
```

Python Version: 3.6.12
ijson Version: 3.1.1

**Comment by rtobar** [comment]
Thanks @lwoerdeman for reporting this. This was indeed a wrong behavior on the `python` backend, which I have now fixed and will soon merge back to the `master` branch (and eventually produce a new release on PyPI, together with other fixes).

While fixing this (and adding tests to ensure it didn't occur in the future) I found two more small problems:
 * JSON numbers containing a decimal point need to be surrounded by at least one digit at each side (e.g., `.1` and `1.` are invalid). The `python` backend also incorrectly allowed these, so I fixed that as well.
 * The `yajl` backend also allows leading zeros. Note that this backend uses yajl version 1.x and has been considered deprecated for a long time. To address this I simply documented the difference in behvaior on the README file.

**Comment by rtobar** [comment]
Fix is now on the `master` branch.

**Comment by lwoerdeman** [comment]
Hey @rtobar, thank you for resolving this issue so quickly. Do you have an expected release date for the fix to be in PyPI?

**Comment by rtobar** [comment]
@lwoerdeman hopefully within one or two days. There is another minor fix I want to include before creating a new patch release, but I need to first make sure it works as expected.

**Comment by rtobar** [comment]
A new 3.1.3 release containing this fix and others is now up in PyPI.
