### ISSUE TITLE
ijson.items prefix doesn't work if key contains "."

### ISSUE THREAD

**Issue by JingfeiPeng** [ICRAR/ijson#41]
Input json file:
```
{
    "0.1": {
      "123":"ok"
    }
}
```

test file:
```
import ijson
filename = "input.json"
with open(filename, 'r') as f:
    objects = ijson.items(f, '0.1')
    cities = (o for o in objects)
    for city in cities:
        print(city)
```
the test file prints nothing.
If I change the key to be "01", and prefix to be "01" then `{"123":"ok"}` prints as expected.

Any help would be appreciated!

**Comment by jpmckinney** [comment]
I think maybe this bug can't be resolved without changing the prefix format.

I think a tuple would be better e.g. `('0.1',)` for this case, or `('0', '1')` for ijson's current behavior.

**Comment by rtobar** [comment]
I believe this is a bug introduced in 3.1 that was recently reported to me privately, but haven't had a chance to push a fix for yet (just time, not complexity). Can you try with ijson < 3.1 to confirm?

**Comment by JingfeiPeng** [comment]
Verified that this example works with ijson==3.0.4. Thank you!

**Comment by JingfeiPeng** [comment]
Is there a way to select entries for multiple prefixes at one time?

@jpmckinney based on your comment, I thought `("0.1","earth")` would do that but this doesn't work for both version 3.0.4 and 3.1.3

```
filename = "data.json"
with open(filename, 'r') as f:
    for val in ijson.items(f, ("0.1",'earth')):
        print(val)
```

```
{
    "earth": {
      "europe": 1
    },
    "0.1": {
      "123":"ok"
    }
}
```
Expected behavior is to return both `{"123":"ok"}` and `{"europe": 1}`.
Thanks!

**Comment by jpmckinney** [comment]
Sorry, @JingfeiPeng, I was just suggesting an alternative API in which prefixes would be unambiguous. You might want to open a new issue for your feature request.

**Comment by rtobar** [comment]
@JingfeiPeng you can use the `kvitems` method to achieve that with an empty prefix.

**Comment by rtobar** [comment]
Note also that this problem was specific to the `yajl2_c` backend.

**Comment by rtobar** [comment]
@jpmckinney what cannot be currently done is differentiate between different depths. So the following is true (except in the " `yajl2_c` backend because of the current bug):

```python
>>> import ijson
>>> list(ijson.items(b'{"0": {"1": 5}, "0.1": 6}', '0.1'))
[5, 6]
```

Fixing this I think would require a change in the prefix construction rules, like escaping `.`s or similar. If this becomes a problem it's something that could potentially be implemented.

The multiple-prefix feature is also something that sometimes arises, but `kvitems` seems to be a good alternative to most people.

**Comment by jpmckinney** [comment]
Thanks - it's not an issue I've encountered before, so no need from me. In similar projects where I need to keep track of the JSON path/prefix, I've found it easier to work with tuples than to construct strings. Strings end up being ambiguous, unless you implement escaping, which is its own headache.

**Comment by rtobar** [comment]
A fix has been released on the `master` branch, and a new version of ijson will be published soon including this fix. New unit tests have also been added to ensure this problem doesn't creep up again.

**Comment by rtobar** [comment]
ijson 3.1.4, containing a fix for this issue, is now available on PyPI.
