### ISSUE TITLE
IncompleteJSONError is not recognized for null and boolean values

### ISSUE THREAD

**Issue by harpener** [ICRAR/ijson#42]
Hi guys,

we are using this library to be able to parse incomplete JSON, specifically its Python backend.

We noticed that sometimes it raises `UnexpectedSymbol` instead of `IncompleteJSONError` and after some investigation, we found out that the problem is that given JSON ended with incomplete `null` or `true` or `false` value. E.g. `{"a": n`. It seems that the lexer's state machine does not recognize it.

Do you think this is a valid case and if so, can it be fixed?

Thank you for your response.

**Comment by rtobar** [comment]
@harpener if I understand correctly, your concern is that the type of exception raised by the code is not what you expected, and therefore you can't recognize the particular problem of an incomplete JSON document, right?

You are right that the `python` backend doesn't recognise these cases properly, so yes, this can be improved. On the other hand this is the slowest backend; the others *do* raise `IncompleteJSONError` on these cases, so you might be better off using those anyway. I will still improve the `python` backend to detect these cases and raise the appropriate exception.

**Comment by rtobar** [comment]
A fix for this is now on the `master` branch; now the `python` backend recognises incomplete JSON tokens like `tru` or `nu` as such and raises an `IncompleteJSONError` exception.

**Comment by harpener** [comment]
Thanks for the fix. I haven't even been able to import any of the yajl backends on local Windows or production Linux environments, so I can't say how they behave. But the performance is not that important for now.

**Comment by rtobar** [comment]
ijson 3.1.4 is now available on PyPI
