### ISSUE TITLE
How to fix IncompleteJSONError

### ISSUE THREAD

**Issue by ShawnLin-pku** [ICRAR/ijson#50]
I have come across the error when using ijson to parse big json file
```
IncompleteJSONError: lexical error: invalid char in json text.
                        {      "_id" : ObjectId("5e5d193d8cf3fe97fa488
                     (right here) ------^
```
My source code is as followed:
```python
with codecs.open('lagou.json','rb') as f:
    objects = ijson.items(f,'item')
    print(objects.__next__())
```
It really confuses me that why character 'b' will be a invalid char

**Comment by rtobar** [comment]
(I took the liberty of editing the original question for correct formatting)

@ShawnLin-pku your JSON document is not valid: `ObjectId` is not a valid token in JSON. It looks like you have a document that *looks* like JSON, but isn't strictly JSON.

**Comment by ShawnLin-pku** [comment]
> (I took the liberty of editing the original question for correct formatting)
> 
> @ShawnLin-pku your JSON document is not valid: `ObjectId` is not a valid token in JSON. It looks like you have a document that _looks_ like JSON, but isn't strictly JSON.

Thanks for your reply. I exported this document from mongo database. So how can I load this file using ijson's iterator? (It's so big that I can't load it directly in memory)

**Comment by rtobar** [comment]
@ShawnLin-pku you can't load it with `ijson` because it's not a valid JSON document, it just looks very much like one.
