### ISSUE TITLE
Support/Builds for Python 3.10

### ISSUE THREAD

**Issue by jnsdrtlf** [ICRAR/ijson#69]
## Problem

While you can without a problem install `ijson` using `pip` on Python 3.10, **only the `python` backend will be available**. This is because the binary wheels that include the `yajl` backends are only build for Python 3.9 and older versions.

## Possible Solution

Support for Python 3.10 should be a non-issue as there appear to be no breaking changes introduced in 3.10 that would interfere with the `yajl` backends (see **Additional Context**).

I propose to release a new version (if this is even necessary?) and adjust the `.travis.yml` build file to include Python 3.10. You may also consider changing `3.9-dev` to `3.9` in this line:

https://github.com/ICRAR/ijson/blob/f2ed122298a24b748f7a7f3c5dd197bba16b4421/.travis.yml#L86

Additionally, meta data in the `setup.py` file has to be updated to indicate support for 3.10.

## Additional Context

I cloned the project, installed `yajl` using the provided script in the `.github/tools` directory, build a wheel for Python 3.10 using `python setup.py bdist_wheel` and installed it. I can confirm that - at least on macOS 12.3 - **all tests passed without issues**. I did however not run any performance benchmarks.

**Comment by jnsdrtlf** [comment]
Seems like I missed π-day (03/14) by a day. What a missed opportunity! Especially as `ijson` is currently on version `3.1.4` :weary:. But at least I proposed a version bump to (maybe) `3.1.5` on 03/15...

**Comment by rtobar** [comment]
@jnsdrtlf what platform are you on? There should be a binary wheel for 3.10, Linux. See #63 for more details.

**Comment by jnsdrtlf** [comment]
macOS 12.3 on my local machine but we run Linux in production and indeed, the `yajl` backend is available on Linux for Python 3.10.

**Comment by jnsdrtlf** [comment]
And sorry, I did not check the closed issues and completely missed you previous statements 😅

**Comment by rtobar** [comment]
@jnsdrtlf yeah, I also missed you were using MacOS, but good to know that in production you're using Linux, so you should be covered. If you agree I'll close this one, you'll have to be a bit patient and wait to get a binary wheel on your Mac when I publish the next version of ijson.

**Comment by jnsdrtlf** [comment]
Works for me 👍🏽

**Comment by ElLorans** [comment]
Still on version 3.1.4, same issue on Python 3.10 for Windows =(

**Comment by rtobar** [comment]
Yeap, same answer from my side: please be patient and wait for a new ijson release for binary wheels to be generated for all platforms. Alternatively you can build ijson with the yajl2_c backend in Windows (we do that with cibuildwheel and embedding the yajl sources in the C extension, see setup.py and the cibuildwheel env variables we set in Travis for details).

**Comment by sweetpythoncode** [comment]
@rtobar Do we have a chance to build wheels(yajl2_c) for python 3.11 on ubuntu, It will be very helpful based on the speed-up update with python 3.11, please.

**Comment by rtobar** [comment]
@sweetpythoncode if when you say "we" you mean "anyone", then yes, you can always compile the package locally to generate a binary wheel, if that's what you are asking. I tested a while ago compiling ijson against python 3.11 and didn't find any problems, so I'd expect no surprises.

If what you're asking is whether **I** can publish binary wheels for 3.11 in PyPI I'm afraid the answer is the same as above: please be patient, they'll come later.

**Comment by rtobar** [comment]
For those in this issue: a new version of ijson has been released, including binary wheels for 3.11.
