### ISSUE TITLE
How to determine which backend is being used at runtime?

### ISSUE THREAD

**Issue by petrock99** [ICRAR/ijson#81]
**Description**
How to determine which backend is being used at runtime?

**Detailed description**
If I have cffi & yajl packages installed it will pick the yaml2 backend, otherwise the python backend. Cool. It took me a while to figure this out via stepping through the code etc. Is there an easier way? Is there an API that will return the name of the current backend?

My use case was doing some 'wall clock' & 'memory usage' performance tests & tuning against a very large JSON file for my project. It took me a while to figure out why it performed better in one conda environment (which had ijson, cffi, yajl and bunch of other stuff installed) than it did on another bare bones conda environment with almost nothing but python & ijson installed. 

**Why is this not clear from the documentation**
The documentation show how to choose a backend, not how to determine which one is actually being used.

**Comment by rtobar** [comment]
In https://github.com/ICRAR/ijson#backends it is mentioned that "and its name is recorded under i`json.backend`", but I can see how it's not super clear -- it's only mentioned in the context of importing ijson as a whole, not when importing a specific backend.

The text should read that the backend name is stored under the `backend` attribute of each backend, which is the answer you're looking for.

**Comment by rtobar** [comment]
Since this has been answered I'm declaring it closed. Please re-open if more clarification is needed.

**Comment by petrock99** [comment]
Thank you for the reply. Yes, that solution works nicely. Thanks.
