### ISSUE TITLE
High level interface to iterate over lists

### ISSUE THREAD

**Issue by TekTimmy** [ICRAR/ijson#83]
**Is your feature request related to a problem? Please describe.**
I have a JSON with a very large list of objects:
```json
{
  "Modifications": [
    {"object_number": 1},
    {"object_number": 4532432}
  ]
}
```

**Describe the solution you'd like**
I would like to have a high level method to iterate over each entry in the `Modifications` list without having to use the low level API.

**Describe alternatives you've considered**
use the low level API

**Additional context**

**Comment by rtobar** [comment]
@TekTimmy Could you describe in more detail (some code) what were you trying? It sounds like what you want should be possible already using `ijson.items(f, "Modifications.item")` (with `f` being your opened file-like object where we can read the JSON data from), and indeed it's the usual go-to method that most people use.

**Comment by rtobar** [comment]
@TekTimmy hello?

**Comment by TekTimmy** [comment]
Sorry for the late reply @rtobar ! Yes you are right, I did not try that because from the docs I understood that its for iterating object members only.. Thank you!
