### ISSUE TITLE
Is it possible to use multiple prefix

### ISSUE THREAD

**Issue by ManivannanMurugavel** [ICRAR/ijson#85]
My expectation is
```
Input:
[
    {
        "name": "abc",
        "age": "21",
        "studies": [
            {
                "subname": "tamil",
                "grade": "a"
            },
            {
                "subname": "eng",
                "grade": "a"
            }
        ]
    },
    {
        "name": "xyz",
        "age": "24",
        "studies": [
            {
                "subname": "science",
                "grade": "c"
            },
            {
                "subname": "math",
                "grade": "e"
            }
        ]
    }
]

Output:
[
    {
        "name": "abc",
        "age": "21",
        "subname": "tamil",
        "grade": "a"
    },
    {
        "name": "abc",
        "age": "21",
        "subname": "eng",
        "grade": "a"
    },
    {
        "name": "xyz",
        "age": "24",
        "subname": "science",
        "grade": "c"
    },
    {
        "name": "xyz",
        "age": "24",
        "subname": "math",
        "grade": "e"
    }
]
```

Please anyone suggest me how to solve this problem using only ijson.items.
ijson.parse is possible to get this exact output, but i need to use the ijson.items.

Please help me to resolve this issue.

Thanks,
Manivannan

**Comment by rtobar** [comment]
You can do that by iterating over the students with`ijson.items` but you'll have to do do the extra expansion over their studies yourself. Something like:

```python
for student in ijson.items(f, 'item'):
    for study in student['studies']:
        yield {
            'name': student['name'],
            'age': student['age'],
            'subname': study['subname'],
            'grade': study['a'],
        }
```

**Comment by ManivannanMurugavel** [comment]
@rtobar 
Thanks for your reply. 
My scenario is totally different... 
Only I mentioned two dict in the studies list, but I have more than 10k json in studies list. 

If I am using student["studies"], the more than 10k json stored in memory. So this solution not support for me I think. 


Please suggest any other way is available to expect my output.

**Comment by rtobar** [comment]
You'll just have to use `ijson.parse` I'm afraid

**Comment by ManivannanMurugavel** [comment]
Is it possible to use without ijson.parse? 

Is it similar parse and items? 
Because parse is the low level interface right you mentioned

**Comment by rtobar** [comment]
Yes, `ijson.parse` is a lower level interface, but it works well and is documented too. Like I said, this is what you'll need to use, `ijson.itens` won't help in this case.

**Comment by ManivannanMurugavel** [comment]
@rtobar,
Thank you for your reply.

I just altered the ```items_basecoro``` function and the updated the code is below.
```
ijson.common.py

@utils.coroutine
def items_basecoro(target, prefix, map_type=None):
    '''
    An couroutine dispatching native Python objects constructed from the events
    under a given prefix.
    '''
    while True:
        current, event, value = (yield)
        for pre in prefix:
            if current == pre:
                if event in ('start_map', 'start_array'):
                    object_depth = 1
                    builder = ObjectBuilder(map_type=map_type)
                    while object_depth:
                        builder.event(event, value)
                        current, event, value = (yield)
                        if event in ('start_map', 'start_array'):
                            object_depth += 1
                        elif event in ('end_map', 'end_array'):
                            object_depth -= 1
                    del builder.containers[:]
                    target.send(builder.value)
                else:
                    target.send(value)

items = ijson.items(json_string.encode('utf-8'), ("item.name", "item.studies.item"))
```
This is the updation. I know this is not working for global but this is working for my scenario. Because I didn't use the 'item' in the prefix list.

My question is:
1) Is this way good or any problem using list of prefix?
2) Is there any otherway without touching your code.

Please help me..


Thanks,

**Comment by rtobar** [comment]
@ManivannanMurugavel I'm not sure whether your code is correct or not, since other than giving you advice I can't really spend time in helping you with specific details of your problem.

Like I mentioned before, you can definitely use `ijson.parse` to achieve your goal (and actually the code above is basically using that), and reading the documentation should give you a good idea of what you need to do.

**Comment by ManivannanMurugavel** [comment]
@rtobar 
Thank you for your help. 
I am closing this..
