### ISSUE TITLE
yajl2_c backend for lambda function

### ISSUE THREAD

**Issue by manifiserv** [ICRAR/ijson#86]
I am using the ijson in aws lambda function. But i couldn't use the `yajl2_c` backend. 
What is the steps follow to setup the `yajl2_c` this backend?

@rtobar 
Please help me resolve the issue.

**Comment by rtobar** [comment]
Sorry, I don't use AWS Lamba, so I won't be able to help. I'd suggest you ask in StackOverflow, providing as many details as possible so someone can help you.

**Comment by manifiserv** [comment]
How will setup in windows?
