### ISSUE TITLE
How to use ijson to covert string to dict?

### ISSUE THREAD

**Issue by kellenf** [ICRAR/ijson#87]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. It would be great if it was possible for ijson to [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered, and why/how they failed.

**Additional context**

**Comment by kellenf** [comment]
I notice that ijson can't convert str object to dict? Can you support this feature?

**Comment by rtobar** [comment]
@kellenf please fill the original issue description as requested, otherwise there's very little I can help with.

**Comment by rtobar** [comment]
Closing as inactive.
