### ISSUE TITLE
Add multiple_values support to Python backend

### ISSUE THREAD

**Issue by jpmckinney** [ICRAR/ijson#9]

**Comment by rtobar** [comment]
Yes, I realised about this when fixing the support for multiple values in the C backend.

For reference, the `yajl` backend (based on yajl 1) also doesn't offer the flag, and it *always* supports multiple values (i.e., it doesn't throw errors when presented with multiple values). This apparently was a limitation of yajl 1.x, but I wouldn't worry about it as the backend has been advertised as deprecated for years.

The python backend indeed also doesn't offer the flag, and by default it *doesn't* support multiple values. This is what would have to be implemented.

**Comment by rtobar** [comment]
OK, this is implemented now on the `master` branch. I'm leaving this open for you to close after confirming this is working as expected.

**Comment by jpmckinney** [comment]
Works great, thanks!
