### ISSUE TITLE
_yajl2 backend broken with Python 3.12

### ISSUE THREAD

**Issue by mgorny** [ICRAR/ijson#98]
**Describe the bug**
The C `_yajl2` extension uses symbols that no longer exist in Python 3.12 and fails to load.

The build yields the following warning:
```
ijson/backends/yajl2_c/parse_basecoro.c: In function ‘parse_basecoro_send_impl’:
ijson/backends/yajl2_c/parse_basecoro.c:93:21: warning: implicit declaration of function ‘PyUnicode_GET_SIZE’; did you mean ‘PyDict_GET_SIZE’? [-Wimplicit-function-declaration]
   93 |                 if (PyUnicode_GET_SIZE(last_path) > 0) {
      |                     ^~~~~~~~~~~~~~~~~~
      |                     PyDict_GET_SIZE
```

Importing the module fails:
```
$ python -c 'import ijson.backends._yajl2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /tmp/ijson/.tox/py312/lib/python3.12/site-packages/ijson/backends/_yajl2.cpython-312-x86_64-linux-gnu.so: undefined symbol: PyUnicode_GET_SIZE
```

**How to reproduce***
Install yajl2 and run `python3.12 setup.py build`.

**Expected behavior**
A working extension module ;-).

**Execution information:**
 - Python version: 3.12.0b2
 - ijson version: 3.2.1 (f69f13abc9c5d47d9ac9da4631d2e4fca1e18d87)
 - ijson backend (if applies): yajl2_c
 - ijson installation method: tested using `pip install .` and direct `python setup.py build`
 - OS: Gentoo Linux amd64

**Additional context**
It looks that the extension is not tested properly — all tests passed, so I've missed the problem initially.

**Comment by rtobar** [comment]
@mgorny thanks for the further report. The CI tests didn't catch this, partly because cibuildwheel isn't building/testing against 3.12 yet.

> It looks that the extension is not tested properly — all tests passed, so I've missed the problem initially

You are right, but up to a point. The tests are written in a way that they go through the backends that can be loaded, because we don't know in advance which ones will be available at runtime (as it depends on cffi and/or libyajl2.so being available, for instance). In other words, importing a backend in itself is not an issue, but this particular failure is. I'm not sure we can test this automatically without too much imagination though, but I'm open for ideas/PRs.

**Comment by mgorny** [comment]
FWICS `ImportError` doesn't provide a way to query why import failed. However, I have one idea: we could use `importlib.util.find_spec()` to check if the module/extension exists. It returns `None` when it doesn't exist, and a `ModuleSpec` when it does (even if it would fail to import).

```
>>> importlib.util.find_spec("ijson.backends.foo")                                                                                    
>>> importlib.util.find_spec("ijson.backends._yajl2")                                                                                 
ModuleSpec(name='ijson.backends._yajl2', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x7efc1e850fb0>, origin='/usr/lib/python3.12/site-packages/ijson/backends/_yajl2.cpython-312-x86_64-linux-gnu.so')
```

**Comment by rtobar** [comment]
@mgorny thanks for that PR. I'll leave minor comments there, but it looks pretty much how I would have done it myself.

While fixing this module loading issue and running the tests I also found that the async generators in the C extension are also broken in 3.12, so I'll need to fix those.

**Comment by rtobar** [comment]
@mgorny I've pushed a number of python3.12-related fixes to the `python3.12-fixes` branch. With those changes I can build the C extension, and run all the tests (and have them pass!). Could you have a look at your end and double-check that all works correctly too? When running the tests make sure the C extension is tested -- for which you might want to do something around `python setup.py develop` followed by `pytest -v` (or similar).

**Comment by mgorny** [comment]
Ah, sorry, I'll look at it right now.

**Comment by mgorny** [comment]
Thank you. I have good news and bad news.

I've noticed that we were testing it wrong in Gentoo, and it missed the C extension indeed. I've fixed that and confirmed that with the patches from the branch, CPython 3.10-3.12 passes all tests.

Bad news is that the test suite crashes with PyPy3.10. I'm going to investigate and file a separate bug for that in a minute.

**Comment by rtobar** [comment]
Thanks for the confirmation and the further issue reported in #101. I've just merged the `python3.12-fixes` branch onto `master`, plus a small mention of the fixes in the `CHANGELOG` file, so I'm closing this issue now.
